### ISSUE TITLE
no longer does playback

### ISSUE THREAD

**Issue by noideaman** [gurrrrrrett3/vrchat-jellyfin#4]
I am no longer getting playback.
VLC and MPV errors as shown

```
Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.5.100:4000/v/rz6ppf18z0h'. Check the log for details.
```

```
mpv http://192.168.5.100:4000/v/x2syon6r95
Failed to recognize file format.
Exiting... (Errors when loading file)
```
logs from vrchat-jellyfin program
```
21:04:49 0|vrc-jellyfin  | Requesting video stream from https://jellyfin/Videos/undefined/stream.mp4?api_key=<KEY>&audioCodec=aac&videoCodec=h264&maxAudioChannels=2&subtitleStreamIndex=0&audioStreamIndex=0&subtitleMethod=Embed  
21:04:49 0|vrc-jellyfin  | Piping stream to client
```

**Comment by gurrrrrrett3** [comment]
odd, also getting this for only some of my files, let me test something

**Comment by gurrrrrrett3** [comment]
could you test the code I just pushed?

**Comment by noideaman** [comment]
still does not do playback

**Comment by gurrrrrrett3** [comment]
```
21:04:49 0|vrc-jellyfin  | Requesting video stream from https://jellyfin/Videos/undefined/stream.mp4?api_key=<KEY>&audioCodec=aac&videoCodec=h264&maxAudioChannels=2&subtitleStreamIndex=0&audioStreamIndex=0&subtitleMethod=Embed  
```
does this link still have undefined as the video id

**Comment by noideaman** [comment]
`Requesting video stream from https://jellyfin/Videos/0ef36ef68d03f3bcb0b6ebc6647e818b/stream.mp4?api_key=<KEY>&audioCodec=aac&videoCodec=h264&maxAudioChannels=2&subtitleStreamIndex=0&audioStreamIndex=0&subtitleMethod=Embed`

**Comment by gurrrrrrett3** [comment]
are you using `jellyfin` as your jellyfin host

**Comment by noideaman** [comment]
i am hiding the full name as it is also forward facing, i have not changed this value from when it worked to now

**Comment by gurrrrrrett3** [comment]
alright, thanks, I'm not able to recreate the issue but I'll keep messing with it

**Comment by noideaman** [comment]
ok some videos work, others do not

**Comment by noideaman** [comment]
looks like if they are not h264 as source it fails to load

**Comment by gurrrrrrett3** [comment]
okay, will see if I can force jellyfin to transcode them

**Comment by gurrrrrrett3** [comment]
hey, did a ton of testing, everything plays fine on my end, make sure you have hardware encoding set up correctly in jellyfin. could you try disabling hardware transcoding if you have it enabled and testing again?

**Comment by gurrrrrrett3** [comment]
also added a js file you can edit to change the encoding settings

**Comment by noideaman** [comment]
should be fine
hooked up to an A380
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/39884745/be9c62b3-a794-4fb7-8490-60a8ffb0314e)

**Comment by noideaman** [comment]
i grabed the link from the programs output, it plays but it does not seem to transcode? so i guess a setting is missing somewhere?
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/39884745/9879d0bc-1086-49c1-9b69-96d7f059978f)

**Comment by gurrrrrrett3** [comment]
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/61361654/7c03681e-ccb2-4b33-b49c-5600a4132e3f)
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/61361654/e923cb99-c9f0-4549-9ee3-9eb8ea8a5175)
it's playing fine on my end, tested HVEC and h265, also using hardware transcoding

**Comment by noideaman** [comment]
yeah so jellyfin does transcode, but for some reason it being handed off to the vrchat-jellyfin is failing for me. i will try digging some more

**Comment by gurrrrrrett3** [comment]
will also look into it, I'm just directly piping the stream through so it shouldn't cause any issues

**Comment by gurrrrrrett3** [comment]
in my setup I have vrcj on the same machine, not using nginx to proxy or anything 
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/61361654/f9a2da3f-c01d-4fa2-9d92-e80af59cf0b4)

**Comment by noideaman** [comment]
i can give that a try. how are you running jellyfin? mine is using the offical docker container, is on 10.9.6

**Comment by noideaman** [comment]
so it fails with localhost and internal ip, inside and outside of docker. for non h264 streams

**Comment by noideaman** [comment]
ok weird, it is not soley hevc
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/39884745/04467959-4d92-40b3-a36b-d55438c833a0)
it played hevc here

**Comment by gurrrrrrett3** [comment]
> i can give that a try. how are you running jellyfin? mine is using the offical docker container, is on 10.9.6

using the linuxserver.io docker container, not using host networking 

```yaml
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /home/server/config/jellyfin:/config
      - /home/server/cache/jellyfin:/cache
      - /home/server/data/media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    ```
